
#ifndef RENDERERFILAMENTLIB_EXPORT_H
#define RENDERERFILAMENTLIB_EXPORT_H

#ifdef RENDERERFILAMENTLIB_STATIC_DEFINE
#  define RENDERERFILAMENTLIB_EXPORT
#  define RENDERERFILAMENTLIB_NO_EXPORT
#else
#  ifndef RENDERERFILAMENTLIB_EXPORT
#    ifdef RendererFilamentLib_EXPORTS
        /* We are building this library */
#      define RENDERERFILAMENTLIB_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define RENDERERFILAMENTLIB_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef RENDERERFILAMENTLIB_NO_EXPORT
#    define RENDERERFILAMENTLIB_NO_EXPORT 
#  endif
#endif

#ifndef RENDERERFILAMENTLIB_DEPRECATED
#  define RENDERERFILAMENTLIB_DEPRECATED __declspec(deprecated)
#endif

#ifndef RENDERERFILAMENTLIB_DEPRECATED_EXPORT
#  define RENDERERFILAMENTLIB_DEPRECATED_EXPORT RENDERERFILAMENTLIB_EXPORT RENDERERFILAMENTLIB_DEPRECATED
#endif

#ifndef RENDERERFILAMENTLIB_DEPRECATED_NO_EXPORT
#  define RENDERERFILAMENTLIB_DEPRECATED_NO_EXPORT RENDERERFILAMENTLIB_NO_EXPORT RENDERERFILAMENTLIB_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef RENDERERFILAMENTLIB_NO_DEPRECATED
#    define RENDERERFILAMENTLIB_NO_DEPRECATED
#  endif
#endif

#endif /* RENDERERFILAMENTLIB_EXPORT_H */
